# Generated by Django 4.2.2 on 2023-06-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='files/resumes'),
        ),
    ]
