# Generated by Django 4.2.2 on 2023-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_resume_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
    ]
