# Generated by Django 4.2.2 on 2023-06-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('large_image', models.ImageField(blank=True, upload_to='img/projects')),
                ('small_image', models.ImageField(blank=True, upload_to='img/projects')),
                ('link', models.URLField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['created_at'],
            },
        ),
    ]
