# Generated by Django 4.2.2 on 2023-06-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='projects/largeimages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='projects/smallimages'),
        ),
    ]
