# Generated by Django 4.2.2 on 2023-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_large_image_alter_project_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
