# Generated by Django 4.2.2 on 2023-06-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtype',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Education Types'},
        ),
    ]
