# Generated by Django 4.2.2 on 2023-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='static/img/company')),
                ('last_job_title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('full_start_date', models.CharField(max_length=100)),
                ('full_end_date', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Employers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['created_at'],
            },
        ),
    ]
