# Generated by Django 4.2.2 on 2023-06-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_job_end_date_alter_job_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='full_end_date',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='full_start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='experience.employer'),
        ),
    ]
