# Generated by Django 4.2.2 on 2023-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_remove_employer_full_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='start_end_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_end_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
