# Generated by Django 4.2.2 on 2023-06-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_employer_start_end_date_job_start_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='experience.job')),
            ],
            options={
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['created_at'],
            },
        ),
    ]
