# Generated by Django 4.2.2 on 2023-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_remove_job_description_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
