# Generated by Django 4.2.2 on 2023-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_alter_jobdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
