# Generated by Django 4.2.2 on 2023-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_jobdescription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='employers/logos'),
        ),
    ]
