# Generated by Django 4.2.2 on 2023-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_alter_employer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='collapse_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
