# Generated by Django 4.2.2 on 2023-06-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_employer_collapse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='multi_jobs',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
    ]
