# Generated by Django 4.2.2 on 2023-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0010_employer_multi_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
