# Generated by Django 4.2.2 on 2023-06-26 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0012_remove_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
