# Generated by Django 4.2.2 on 2023-06-26 23:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0014_remove_jobdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
